[package]
authors = ["Collins Muriuki <hello@collinsmuriuki.xyz>"]
name = "simple_cache"
description = "Simple rust caching tools"
keywords = ["caching"]
license = "MIT"
readme = "./README.md"
version ="1.0.0-beta"

[workspace.package]
authors = ["Collins Muriuki <hello@collinsmuriuki.xyz>"]
version = "1.0.0-beta"
description = "Simple rust caching tools"
edition = "2021"
keywords = ["caching"]
repository = "https://github.com/collinsmuriuki/simple_cache"
readme = "./README.md"
license = "MIT"

[dependencies]
simple_cache_macros = {version="1.0.0-beta", path = "./macros"}

[workspace]
members = [
    "core",
    "macros",
]
