[package]
name = "simple_cache"
version = "1.0.0-beta"
edition = "2021"

[dependencies]
simple_cache_macros = { version = "0.1.0", path = "./macros"}

[workspace]
members = [
    "core",
    "macros",
]
