[package]
name = "simple_cache_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "*"
proc-macro2="*"
syn = {version="*", features=["extra-traits", "full"]}
simple_cache_core={path="../simple_cache_core"}
once_cell = "1.17.1"
