[package]
name = "simple_cache_macros"
version = "1.0.0-beta"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "*"
proc-macro2="*"
syn = {version="*", features=["extra-traits", "full"]}
simple_cache_core={path="../core"}