name: publish to crates.io

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  publish_to_crate_io:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
    - name: Publish to crates.io
      run: |
        cargo doc
        cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}
        cargo publish
  
  sync_docs_to_gh_pages:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
          python-version: '3.10'
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
    - name: Sync Docs
      run: |
        cargo doc
        pip install ghp-import
        echo '<meta http-equiv=refresh content=0;url=mpesa/index.html>' > target/doc/index.html
        ghp-import -n target/doc
        git push -qf https://github.com/collinsmuriuki/simple_cache.git gh-pages
